<?php

class BookingController extends RestController {

    public function restEvents() {
        $this->onRest('req.get.bookingList.render', function () {
            $date = date('Y-m-d');
            $bQuery = "booking_date != '{$date}'";
            if(isset($_GET['q'])){
                $q = $_GET['q'];
                $bQuery .= " and (booking_no like '%{$q}%' or name like '%{$q}%')";
            }
            $bookingArr = array();
            $bookings = NatcBooking::model()->findAll("$bQuery order by booking_date asc limit 20");
            foreach ($bookings as $key => $booking) {
                $bookingArr[$key] = $booking->attributes;
                $rates = NatcDestinationRates::model()->findByPk($booking->dr_id);
                if($booking->vehicle_type == 'Van'){
                    $bookingArr[$key]['rates'] = $rates->dr_rate_van;
                }
                if($booking->vehicle_type == 'Innova'){
                    $bookingArr[$key]['rates'] = $rates->dr_rate_innova;
                }
            }
            echo $this->restJsonEncode($bookingArr);
        });

        $this->onRest('req.get.quickBook.render', function () {
            $booking = new NatcBooking();
            $booking->booking_date = date('Y-m-d');
            $booking->booking_fare = 0;
            $booking->booking_no = 'none';
            $booking->booking_time = date('H:i:s');
            $booking->driver_id = 0;
            $booking->dr_id = 0;
            $booking->vehicle_id = 0;
            $booking->email = 'quickBooking';
            $booking->luggage = 1;
            $booking->name = "Generated by Quick Booking";
            $booking->notes = "Generate by Quick Booking";
            $booking->passengers = 1;
            $booking->phone = "(+63)00-000-0000";
            $booking->vehicle_type = 'Innova';
            $booking->status = 1;
            $booking->pickup = Yii::app()->user->getUser('terminal');
            if($booking->save()){
                $bookingNo = strtoupper(substr(md5(base64_encode($booking->booking_id.$booking->booking_date."natc".$booking->booking_time)), 0, 10));
                $booking->booking_no = $bookingNo;
                $booking->save();
                echo $this->restJsonEncode("success");
            }

        });

        $this->onRest('req.post.assignCab.render', function ($data) {
            $assignBooking = new NatcAssignBooking();
            $assignBooking->vd_id = $data['vdId'];
            $assignBooking->booking_id = $data['bookingId'];
            $assignBooking->status = 1;
            $assignBooking->date_assigned = date('Y-m-d');
            if($assignBooking->save()){
                $vd = NatcVehicleDriver::model()->findByPk($assignBooking->vd_id);
                $vd->availability = 'assigned';
                $vd->save();
                $booking = NatcBooking::model()->findByPk($data['bookingId']);
                $booking->vehicle_id = $vd->vehicle_id;
                $booking->driver_id = $vd->driver_id;
                $rates = NatcDestinationRates::model()->findByPk($booking->dr_id);
                if($booking->vehicle_type == 'Van'){
                    $booking->rate = $rates->dr_rate_van;
                }
                if($booking->vehicle_type == 'Innova'){
                    $booking->rate = $rates->dr_rate_innova;
                }
                if($booking->save()){
                    $driver = NatcDriver::model()->findByPk($vd->driver_id);
                    $vehicle = NatcVehicles::model()->findByPk($vd->vehicle_id);
                    $to = $booking->email;
                    $subject = "YOUR BOOKING HAS BEEN CONFIRMED";

                    $message = "
                        <html>
                        <head>
                        <title>YOUR BOOKING CONFIRMED</title>
                        </head>
                        <body>
                        <p>You have been assigned with a/an {$booking->vehicle_type} </p>
                        <table style='width: 70%'>
                        <tr>
                        <th>Tracking No.</th>
                        <th>Name</th>
                        <th>Pickup</th>
                        <th>Destination</th>
                        <th>Locations</th>
                        <th>Schedule</th>
                        <th>Rate</th>
                        </tr>
                        <tr>
                        <td>{$booking->booking_no}</td>
                        <td>{$booking->name}</td>
                        <td>{$booking->pickup}</td>
                        <td>{$rates->dr_destination}</td>
                        <td>{$rates->dr_locations}</td>
                        <td>{$booking->booking_date}</td>
                        <td>{$booking->rate} php</td>
                        </tr>
                        </table>
                        <br/>
                        <table style='width: 40%'>
                        <tr>
                        <th>Driver</th>
                        <th>Car Model</th>
                        <th>Plate No.</th>
                        </tr>
                        <tr>
                        <td>{$driver->driver_fullname}</td>
                        <td>{$vehicle->model}</td>
                        <td>{$vehicle->plate_no}</td>
                        </tr>
                        </table>
                        </body>
                        </html>
";

// Always set content-type when sending HTML email
                    $headers = "MIME-Version: 1.0" . "\r\n";
                    $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

                    $headers .= 'From: <booking@natc.com>' . "\r\n";
                    mail($to,$subject,$message,$headers);
                }

                echo $this->restJsonEncode("success");
            }
        });

        $this->onRest('req.get.cancelAssignment.render', function () {
            $bookingId = $_GET['bookingId'];
            $assignBooking = NatcAssignBooking::model()->find("booking_id = {$bookingId}");
            if($assignBooking->delete()){
                $vd = NatcVehicleDriver::model()->findByPk($assignBooking->vd_id);
                $vd->availability = 'free';
                $vd->save();
                $booking = NatcBooking::model()->findbyPk($bookingId);
                $booking->vehicle_id = 0;
                $booking->driver_id = 0;
                $booking->save();
                echo $this->restJsonEncode("success");
            }
        });
        $this->onRest('req.get.cancelBooking.render', function () {
            $bookingId = $_GET['bookingId'];
            $booking = NatcBooking::model()->findbyPk($bookingId);
            $booking->status = 3;
            if($booking->save()){
                echo $this->restJsonEncode("success");
            }
        });

        $this->onRest('req.get.markBookingAsDone.render', function () {
            $bookingId = $_GET['bookingId'];
            $assignBooking = NatcAssignBooking::model()->find("booking_id = {$bookingId}");
            $assignBooking->status = 3;
            if($assignBooking->save()){
                $vd = NatcVehicleDriver::model()->findByPk($assignBooking->vd_id);
                $vd->availability = 'free';
                $vd->save();
                $booking = NatcBooking::model()->findbyPk($bookingId);
                $booking->status = 2;
                $booking->save();
                echo $this->restJsonEncode("success");
            }
        });

        $this->onRest('req.get.updateStatus.render', function () {
            $bookingId = $_GET['bookingId'];
            $status = $_GET['status'];
            $assignBooking = NatcAssignBooking::model()->find("booking_id = {$bookingId}");
            $assignBooking->assign_status = $status;
            if($assignBooking->save()){
                echo $this->restJsonEncode("success");
            }
        });

        $this->onRest('req.get.bookingListToday.render', function () {
            $bookingArr = array();
            $date = date('Y-m-d');
            $bookings = NatcBooking::model()->findAll("booking_date = '{$date}' and status = 1 order by booking_id desc limit 12");
            foreach ($bookings as $key => $booking) {
                $bookingArr[$key] = $booking->attributes;
                $assigned = NatcAssignBooking::model()->find("booking_id = {$booking->booking_id} and status not in (3, 4)");
                $bookingArr[$key]['assigned'] = 'no';
                $bookingArr[$key]['bstatus'] = 'pending';
                $rates = NatcDestinationRates::model()->findByPk($booking->dr_id);
                if($booking->vehicle_type == 'Van'){
                    $bookingArr[$key]['rates'] = $rates->dr_rate_van;
                }
                if($booking->vehicle_type == 'Innova'){
                    $bookingArr[$key]['rates'] = $rates->dr_rate_innova;
                }

                if($assigned){
                    $bookingArr[$key]['assigned'] = 'yes';
                    $bookingArr[$key]['bstatus'] = 'assigned';
                    $vehicle = NatcVehicles::model()->findByPk($booking->vehicle_id);
                    $driver = NatcDriver::model()->findByPk($booking->driver_id);
                    if($vehicle && $driver){
                        $bookingArr[$key]['vehicle'] = $vehicle->attributes;
                        $bookingArr[$key]['driver'] = $driver->attributes;
                    }
                }
            }
            echo $this->restJsonEncode($bookingArr);
        });
        $this->onRest('req.get.availableVehicles.render', function () {
            $availableArr = array();
            $sql = "select a.*, b.brand, b.plate_no, b.unit_no, b.model, c.driver_fullname, c.driver_license_type
            from natc_vehicle_driver a
            inner join natc_vehicles b on (a.vehicle_id = b.vehicle_id)
            inner join natc_driver c on (a.driver_id = c.driver_id)
            where availability = 'free' and a.status = 'Current' order by vd_id desc";
            $available = NatcVehicleDriver::model()->findAllbySql($sql);
            foreach ($available as $key => $avail) {
                $availableArr[$key] = $avail->attributes;
                $availableArr[$key]['driver'] = $avail->driver_fullname;
                $availableArr[$key]['license'] = $avail->driver_license_type;
                $availableArr[$key]['brand'] = $avail->brand;
                $availableArr[$key]['unit'] = $avail->unit_no;
                $availableArr[$key]['model'] = $avail->model;
                $availableArr[$key]['plate'] = $avail->plate_no;
            }
            echo $this->restJsonEncode($availableArr);
        });
    }
}
